# Basic Packages, Functions and Concepts
- Python numerical types
- Basic mathematical functions
- Numpy arrays
- Matrices

## Python Numerical Types

#### Decimal type
For applications that require decimal digits with accurate arithmetic operations, use the Decimal type from the decimal module in the Python Standard Library

In [1]:
from decimal import Decimal
num1 = Decimal('4.2')
num2 = Decimal('2.1')

num1 + num2

Decimal('6.3')

#### Fraction type
we typically give the numerator and denominator of the fraction as arguments

In [2]:
from fractions import Fraction
num1 = Fraction(4, 10)
num2 = Fraction(6, 15)

num1 + num2

Fraction(4, 5)

#### Complex type
This code creates a complex number z with real part 2 and imaginary part 3. We then use the real and imag attributes to access the real and imaginary parts of z, respectively. The conjugate method returns the complex conjugate of z. The cmath.polar function takes z as an argument and returns a tuple containing the magnitude and phase (in radians) of z.

In [3]:
import cmath

# create a complex number
z = 2 + 3j

# perform various operations with complex numbers
print("Real part:", z.real)
print("Imaginary part:", z.imag)
print("Complex conjugate:", z.conjugate())
print("Magnitude:", cmath.polar(z)[0])
print("Phase (in radians):", cmath.polar(z)[1])


Real part: 2.0
Imaginary part: 3.0
Complex conjugate: (2-3j)
Magnitude: 3.605551275463989
Phase (in radians): 0.982793723247329


## Basic mathematical functions

In [ ]:
import math

# perform square root
x = 25
print("Square root of", x, "is", math.sqrt(x))

# perform logarithm
y = 0.5
print("Base 10 logarithm of", y, "is", math.log10(y))

# perform sine function
z = math.pi/4
print("Sine of", z, "is", math.sin(z))

# perform cosine function
a = math.pi
print("Cosine of", a, "is", math.cos(a))

# perform tangent function
b = math.pi/2
print("Tangent of", b, "is", math.tan(b))

# perform arcsine function
c = 1
print("Arcsine of", c, "is", math.asin(c))

# perform arccosine function
d = 0
print("Arccosine of", d, "is", math.acos(d))

# perform arctangent function
e = 1
print("Arctangent of", e, "is", math.atan(e))


## NumPy arrays

In [4]:
import numpy as np

# create an array
a = np.array([1, 2, 3, 4])
print("Array a:", a)

# perform element-wise addition
b = np.array([5, 6, 7, 8])
print("Array b:", b)
c = a + b
print("Array c (element-wise addition of a and b):", c)

# perform dot product
d = np.dot(a, b)
print("Dot product of a and b:", d)

# perform transpose
e = np.transpose(a)
print("Transpose of a:", e)

# perform reshape
f = a.reshape(2, 2)
print("Reshaped a:", f)

# perform mean
g = np.mean(a)
print("Mean of a:", g)

# perform standard deviation
h = np.std(a)
print("Standard deviation of a:", h)


Array a: [1 2 3 4]
Array b: [5 6 7 8]
Array c (element-wise addition of a and b): [ 6  8 10 12]
Dot product of a and b: 70
Transpose of a: [1 2 3 4]
Reshaped a: [[1 2]
 [3 4]]
Mean of a: 2.5
Standard deviation of a: 1.118033988749895


In [9]:
import numpy as np

# create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Array a:\n", a)

# indexing
print("Element at row 0, column 2:", a[0, 2])

# slicing
b = a[:, 1:]
print("Array b (sliced from array a):\n", b)

# create a boolean mask
mask = a > 3
print("Boolean mask:\n", mask)

# use the boolean mask to extract elements
c = a[mask]
print("Elements from array a that satisfy the mask:", c)

# use the boolean mask to set elements to a value
a[mask] = 0
print("Array a after setting elements to 0:\n", a)

# reshape b to be compatible with a for matrix multiplication
b = b.reshape(3, 2)

# perform matrix multiplication
d = np.dot(a, b)
print("Matrix product of a and b:\n", d)

# perform element-wise multiplication
e = a * b
print("Element-wise product of a and b:\n", e)

# perform sum along an axis
f = np.sum(a, axis=0)
print("Sum of array a along axis 0:", f)

# perform cumulative sum
g = np.cumsum(a)
print("Cumulative sum of array a:", g)

# perform mean along an axis
h = np.mean(a, axis=1)
print("Mean of array a along axis 1:", h)

# perform standard deviation along an axis
i = np.std(a, axis=1)
print("Standard deviation of array a along axis 1:", i)


Array a:
 [[1 2 3]
 [4 5 6]]
Element at row 0, column 2: 3
Array b (sliced from array a):
 [[2 3]
 [5 6]]
Boolean mask:
 [[False False False]
 [ True  True  True]]
Elements from array a that satisfy the mask: [4 5 6]
Array a after setting elements to 0:
 [[1 2 3]
 [0 0 0]]


ValueError: cannot reshape array of size 4 into shape (3,2)

## Matrices

In [1]:
import numpy as np

# create a 2D array
a = np.array([[1, 6], [1, 4]])
print("Array a:\n", a)

# compute the transpose of a matrix
b = np.transpose(a)
print("Transpose of array a:\n", b)

# compute the determinant of a matrix
c = np.linalg.det(a)
print("Determinant of array a:", c)

# perform matrix inversion
d = np.linalg.inv(a)
print("Inverse of array a:\n", d)

# solve a linear system using the LU decomposition
e = np.array([6, 15])
f = np.linalg.solve(a, e)
print("Solution to linear system using LU decomposition:", f)

# perform singular value decomposition
g, h, i = np.linalg.svd(a)
print("Singular value decomposition of array a:\nU:", g, "\nS:", h, "\nV:", i)

# perform eigenvalue decomposition
j, k = np.linalg.eig(a)
print("Eigenvalue decomposition of array a:\nEigenvalues:", j, "\nEigenvectors:", k)

# perform QR decomposition
l, m = np.linalg.qr(a)
print("QR decomposition of array a:\nQ:", l, "\nR:", m)

# perform Cholesky decomposition
n = np.linalg.cholesky(a)
print("Cholesky decomposition of array a:\nL:", n)


Array a:
 [[1 6]
 [1 4]]
Transpose of array a:
 [[1 1]
 [6 4]]
Determinant of array a: -2.0
Inverse of array a:
 [[-2.   3. ]
 [ 0.5 -0.5]]
Solution to linear system using LU decomposition: [33.  -4.5]
Singular value decomposition of array a:
U: [[-0.82806723 -0.56062881]
 [-0.56062881  0.82806723]] 
S: [7.34342046 0.27235265] 
V: [[-0.18910752 -0.98195639]
 [ 0.98195639 -0.18910752]]
Eigenvalue decomposition of array a:
Eigenvalues: [-0.37228132  5.37228132] 
Eigenvectors: [[-0.9748284  -0.80818183]
 [ 0.22295647 -0.58893305]]
QR decomposition of array a:
Q: [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 
R: [[-1.41421356 -7.07106781]
 [ 0.         -1.41421356]]
Cholesky decomposition of array a:
L: [[1.         0.        ]
 [1.         1.73205081]]


In [2]:
import numpy as np
from scipy.sparse import csr_matrix

# create a dense array
a = np.array([[1, 2, 0], [0, 0, 3], [4, 0, 5]])

# convert to sparse matrix in CSR format
b = csr_matrix(a)

# perform matrix addition
c = b + b
print("Sparse matrix addition:\n", c.toarray())

# perform matrix multiplication
d = b.dot(b)
print("Sparse matrix multiplication:\n", d.toarray())

# perform element-wise multiplication
e = b.multiply(b)
print("Sparse matrix element-wise multiplication:\n", e.toarray())

# perform transpose
f = b.transpose()
print("Sparse matrix transpose:\n", f.toarray())

# compute the sum of all elements
g = b.sum()
print("Sum of all elements in the sparse matrix:", g)


Sparse matrix addition:
 [[ 2  4  0]
 [ 0  0  6]
 [ 8  0 10]]
Sparse matrix multiplication:
 [[ 1  2  6]
 [12  0 15]
 [24  8 25]]
Sparse matrix element-wise multiplication:
 [[ 1  4  0]
 [ 0  0  9]
 [16  0 25]]
Sparse matrix transpose:
 [[1 0 4]
 [2 0 0]
 [0 3 5]]
Sum of all elements in the sparse matrix: 15
